import { MockUser, Mood, Interest, Language } from './types';

export const MOCK_USERS: MockUser[] = [
  {
    id: 1,
    name: 'Alex',
    photoUrl: 'https://picsum.photos/seed/alex/200',
    mood: Mood.Exploring,
    interests: [Interest.Coffee, Interest.Music, Interest.Art],
    latitude: 37.78,
    longitude: -122.41,
  },
  {
    id: 2,
    name: 'Bella',
    photoUrl: 'https://picsum.photos/seed/bella/200',
    mood: Mood.Creative,
    interests: [Interest.Art, Interest.Reading, Interest.Movies],
    latitude: 37.76,
    longitude: -122.42,
  },
  {
    id: 3,
    name: 'Charlie',
    photoUrl: 'https://picsum.photos/seed/charlie/200',
    mood: Mood.Chill,
    interests: [Interest.Gaming, Interest.Coding, Interest.Movies],
    latitude: 37.79,
    longitude: -122.4,
  },
  {
    id: 4,
    name: 'Dana',
    photoUrl: 'https://picsum.photos/seed/dana/200',
    mood: Mood.Happy,
    interests: [Interest.Sports, Interest.Music, Interest.Coffee],
    latitude: 37.75,
    longitude: -122.43,
  },
    {
    id: 5,
    name: 'Emi',
    photoUrl: 'https://picsum.photos/seed/emi/200',
    mood: Mood.Chill,
    interests: [Interest.Reading, Interest.Coffee, Interest.Art],
    latitude: 37.77,
    longitude: -122.44,
  },
];

export const ALL_INTERESTS: Interest[] = Object.values(Interest);
export const ALL_MOODS: Mood[] = Object.values(Mood);

export const TEXTS: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    appName: 'Loneliness Map',
    onboardingTitle: 'Welcome!',
    onboardingSubtitle: 'Create a simple profile to connect with others.',
    yourName: 'Your Name',
    yourNamePlaceholder: 'e.g., Alex',
    selectMood: 'Select your current mood',
    selectInterests: 'Select up to 3 interests',
    getStarted: 'Get Started',
    welcomeBack: 'Welcome back,',
    findFriendsPrompt: 'When you feel lonely, just press the button below.',
    findFriendsButton: 'I feel lonely → Find friends nearby',
    nearbyPeople: 'People Nearby',
    sharedInterests: 'Shared Interests',
    chat: 'Chat',
    sendMessage: 'Send Message',
    typeMessage: 'Type a message...',
    close: 'Close',
    gettingLocation: 'Getting your location...',
    locationPermissionDenied: 'Please enable location access to find people nearby.',
    kmAway: 'km away',
  },
  [Language.TH]: {
    appName: 'แผนที่คนเหงา',
    onboardingTitle: 'ยินดีต้อนรับ!',
    onboardingSubtitle: 'สร้างโปรไฟล์ง่ายๆ เพื่อเชื่อมต่อกับผู้อื่น',
    yourName: 'ชื่อของคุณ',
    yourNamePlaceholder: 'เช่น อเล็กซ์',
    selectMood: 'เลือกอารมณ์ปัจจุบันของคุณ',
    selectInterests: 'เลือกความสนใจสูงสุด 3 อย่าง',
    getStarted: 'เริ่มต้นใช้งาน',
    welcomeBack: 'ยินดีต้อนรับกลับ,',
    findFriendsPrompt: 'เมื่อคุณรู้สึกเหงา แค่กดปุ่มด้านล่าง',
    findFriendsButton: 'ฉันรู้สึกเหงา → ค้นหาเพื่อนใกล้ๆ',
    nearbyPeople: 'คนใกล้เคียง',
    sharedInterests: 'ความสนใจร่วมกัน',
    chat: 'แชท',
    sendMessage: 'ส่งข้อความ',
    typeMessage: 'พิมพ์ข้อความ...',
    close: 'ปิด',
    gettingLocation: 'กำลังค้นหาตำแหน่งของคุณ...',
    locationPermissionDenied: 'โปรดเปิดใช้งานการเข้าถึงตำแหน่งเพื่อค้นหาผู้คนในบริเวณใกล้เคียง',
    kmAway: 'กม. ที่อยู่ห่างออกไป',
  },
  [Language.JP]: {
    appName: '孤独マップ',
    onboardingTitle: 'ようこそ！',
    onboardingSubtitle: '簡単なプロフィールを作成して、他の人とつながりましょう。',
    yourName: 'あなたの名前',
    yourNamePlaceholder: '例：アレックス',
    selectMood: '現在の気分を選択してください',
    selectInterests: '興味を3つまで選択してください',
    getStarted: '始める',
    welcomeBack: 'おかえりなさい、',
    findFriendsPrompt: '寂しいと感じたら、下のボタンを押してください。',
    findFriendsButton: '寂しい → 近くの友達を探す',
    nearbyPeople: '近くの人々',
    sharedInterests: '共通の興味',
    chat: 'チャット',
    sendMessage: 'メッセージを送る',
    typeMessage: 'メッセージを入力...',
    close: '閉じる',
    gettingLocation: 'あなたの場所を取得しています...',
    locationPermissionDenied: '近くの人を見つけるには、位置情報へのアクセスを有効にしてください。',
    kmAway: 'km先',
  },
};